"use client";

import { useState, useCallback, useRef, useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import PageTransition from "@/components/PageTransition";
import AdBanner from "@/components/AdBanner";
import { useLocale } from "@/hooks/useLocale";

const translations = {
  ko: {
    title: "제비뽑기",
    subtitle: "공정하고 긴장감 넘치는 온라인 추첨",
    quickStartPresets: "빠른 시작 프리셋",
    itemsLabel: "항목 추가",
    itemsMax: "(최대 20개)",
    itemPlaceholder: "이름 입력 (쉼표로 여러 개)",
    addBtn: "추가",
    itemCount: (n: number) => `${n}개 항목`,
    removeItem: (name: string) => `${name} 제거`,
    winnersLabel: "당첨자 수",
    people: "명",
    winnerRatio: (total: number, win: number, lose: number) =>
      `전체 ${total}개 중 ${win}명 당첨 / ${lose}명 꽝`,
    tooManyWinners: "당첨자 수는 전체 항목보다 적어야 합니다",
    startBtnNeedMore: "항목을 2개 이상 추가하세요",
    startBtnTooMany: "당첨자 수를 줄여주세요",
    startBtn: "🎴 추첨 시작!",
    shuffling: "🔀 카드를 섞는 중...",
    tapToFlip: "카드를 탭해서 뒤집으세요!",
    revealed: (flipped: number, total: number) => `${flipped} / ${total} 공개됨`,
    revealAll: "전체 공개",
    tapToReveal: "탭하여 공개",
    drawComplete: "추첨 완료!",
    drawSummary: (total: number, win: number) => `전체 ${total}개 중 당첨 ${win}명`,
    winners: (n: number) => `당첨 (${n}명)`,
    losers: (n: number) => `꽝 (${n}명)`,
    copyResult: "결과 복사",
    copied: "복사됨!",
    redraw: "다시 뽑기",
    reset: "처음부터",
    faqTitle: "자주 묻는 질문",
    faq: [
      {
        q: "제비뽑기는 어떻게 사용하나요?",
        a: "추첨할 항목(이름, 팀명 등)을 입력하거나 프리셋을 선택한 후 당첨자 수를 정하세요. 추첨 시작 버튼을 누르면 카드가 섞이고, 각 카드를 탭해 당첨 여부를 공개할 수 있습니다.",
      },
      {
        q: "추첨 결과가 정말 공정한가요?",
        a: "네! Fisher-Yates 셔플 알고리즘을 사용해 완전히 무작위로 당첨자를 결정합니다. 사전에 결과가 정해지지 않으며, 누구도 예측하거나 조작할 수 없어 공정한 추첨이 보장됩니다.",
      },
      {
        q: "어떤 상황에서 활용할 수 있나요?",
        a: "당첨자 선발, 벌칙 뽑기, 순서 정하기, 경품 추첨, 파티 게임 등 다양한 상황에서 활용할 수 있습니다. 프리셋으로 당첨/꽝, 1·2·3등 추첨도 바로 시작할 수 있어요.",
      },
    ],
    presets: [
      { label: "당첨/꽝", items: ["당첨", "꽝"] },
      { label: "1·2·3등/꽝", items: ["1등", "2등", "3등", "꽝"] },
      { label: "벌칙 있음/없음", items: ["벌칙", "면제", "면제", "면제"] },
    ],
    copyLines: {
      header: "[제비뽑기 결과]",
      winners: (n: number, names: string) => `당첨 (${n}명): ${names}`,
      losers: (n: number, names: string) => `꽝 (${n}명): ${names}`,
      footer: "PickPlay에서 생성",
    },
  },
  en: {
    title: "Lucky Draw",
    subtitle: "Fair and exciting online lottery",
    quickStartPresets: "Quick Start Presets",
    itemsLabel: "Add Items",
    itemsMax: "(max 20)",
    itemPlaceholder: "Enter names (comma-separated)",
    addBtn: "Add",
    itemCount: (n: number) => `${n} item${n !== 1 ? "s" : ""}`,
    removeItem: (name: string) => `Remove ${name}`,
    winnersLabel: "Number of Winners",
    people: "",
    winnerRatio: (total: number, win: number, lose: number) =>
      `${win} winner${win !== 1 ? "s" : ""} / ${lose} loser${lose !== 1 ? "s" : ""} out of ${total}`,
    tooManyWinners: "Winners must be fewer than total items",
    startBtnNeedMore: "Add at least 2 items",
    startBtnTooMany: "Reduce the number of winners",
    startBtn: "🎴 Start Draw!",
    shuffling: "🔀 Shuffling cards...",
    tapToFlip: "Tap a card to flip it!",
    revealed: (flipped: number, total: number) => `${flipped} / ${total} revealed`,
    revealAll: "Reveal All",
    tapToReveal: "Tap to reveal",
    drawComplete: "Draw Complete!",
    drawSummary: (total: number, win: number) => `${win} winner${win !== 1 ? "s" : ""} out of ${total}`,
    winners: (n: number) => `Winner${n !== 1 ? "s" : ""} (${n})`,
    losers: (n: number) => `Loser${n !== 1 ? "s" : ""} (${n})`,
    copyResult: "Copy Result",
    copied: "Copied!",
    redraw: "Redraw",
    reset: "Start Over",
    faqTitle: "FAQ",
    faq: [
      {
        q: "How do I use Lucky Draw?",
        a: "Enter the items (names, team names, etc.) or choose a preset, then set the number of winners. Press Start Draw and cards will be shuffled — tap each card to reveal whether it's a winner.",
      },
      {
        q: "Is the draw truly fair?",
        a: "Yes! We use the Fisher-Yates shuffle algorithm so every outcome is equally likely. Results are not predetermined and cannot be predicted or manipulated.",
      },
      {
        q: "What situations can I use this for?",
        a: "Winner selection, penalty draws, turn order, raffle prizes, party games, and more. Use presets for Win/Lose or 1st/2nd/3rd place draws.",
      },
    ],
    presets: [
      { label: "Win / Lose", items: ["Win", "Lose"] },
      { label: "1st / 2nd / 3rd / Lose", items: ["1st", "2nd", "3rd", "Lose"] },
      { label: "Penalty / Safe", items: ["Penalty", "Safe", "Safe", "Safe"] },
    ],
    copyLines: {
      header: "[Lucky Draw Result]",
      winners: (n: number, names: string) => `Winner${n !== 1 ? "s" : ""} (${n}): ${names}`,
      losers: (n: number, names: string) => `Loser${n !== 1 ? "s" : ""} (${n}): ${names}`,
      footer: "Generated by PickPlay",
    },
  },
  ja: {
    title: "くじ引き",
    subtitle: "公平でドキドキのオンライン抽選",
    quickStartPresets: "クイックスタート",
    itemsLabel: "項目を追加",
    itemsMax: "（最大20個）",
    itemPlaceholder: "名前を入力（カンマ区切りで複数可）",
    addBtn: "追加",
    itemCount: (n: number) => `${n}個`,
    removeItem: (name: string) => `${name}を削除`,
    winnersLabel: "当選者数",
    people: "人",
    winnerRatio: (total: number, win: number, lose: number) =>
      `全${total}個中 当選${win}人 / ハズレ${lose}人`,
    tooManyWinners: "当選者数は全項目数より少なくしてください",
    startBtnNeedMore: "2つ以上の項目を追加してください",
    startBtnTooMany: "当選者数を減らしてください",
    startBtn: "🎴 抽選スタート！",
    shuffling: "🔀 カードをシャッフル中...",
    tapToFlip: "カードをタップして裏返してください！",
    revealed: (flipped: number, total: number) => `${flipped} / ${total} 公開済み`,
    revealAll: "全て公開",
    tapToReveal: "タップして公開",
    drawComplete: "抽選完了！",
    drawSummary: (total: number, win: number) => `全${total}個中 当選${win}人`,
    winners: (n: number) => `当選（${n}人）`,
    losers: (n: number) => `ハズレ（${n}人）`,
    copyResult: "結果をコピー",
    copied: "コピー済み！",
    redraw: "もう一度",
    reset: "最初から",
    faqTitle: "よくある質問",
    faq: [
      {
        q: "くじ引きの使い方は？",
        a: "項目（名前やチーム名など）を入力するかプリセットを選び、当選者数を決めてください。抽選スタートを押すとカードがシャッフルされ、タップして結果を公開できます。",
      },
      {
        q: "抽選結果は本当に公平ですか？",
        a: "はい！Fisher-Yates シャッフルアルゴリズムで完全にランダムに決定します。事前に結果は決まっておらず、誰も予測・操作できません。",
      },
      {
        q: "どんな場面で使えますか？",
        a: "当選者の選定、罰ゲーム決め、順番決め、景品抽選、パーティゲームなど様々な場面で活用できます。",
      },
    ],
    presets: [
      { label: "当選/ハズレ", items: ["当選", "ハズレ"] },
      { label: "1〜3位/ハズレ", items: ["1位", "2位", "3位", "ハズレ"] },
      { label: "罰ゲーム/セーフ", items: ["罰ゲーム", "セーフ", "セーフ", "セーフ"] },
    ],
    copyLines: {
      header: "[くじ引き結果]",
      winners: (n: number, names: string) => `当選（${n}人）: ${names}`,
      losers: (n: number, names: string) => `ハズレ（${n}人）: ${names}`,
      footer: "PickPlayで生成",
    },
  },
  zh: {
    title: "抽签",
    subtitle: "公平刺激的在线抽签",
    quickStartPresets: "快速开始",
    itemsLabel: "添加选项",
    itemsMax: "（最多20个）",
    itemPlaceholder: "输入名称（逗号分隔多个）",
    addBtn: "添加",
    itemCount: (n: number) => `${n}个选项`,
    removeItem: (name: string) => `移除${name}`,
    winnersLabel: "中签人数",
    people: "人",
    winnerRatio: (total: number, win: number, lose: number) =>
      `共${total}个，中签${win}人 / 未中${lose}人`,
    tooManyWinners: "中签人数必须少于总选项数",
    startBtnNeedMore: "请添加至少2个选项",
    startBtnTooMany: "请减少中签人数",
    startBtn: "🎴 开始抽签！",
    shuffling: "🔀 正在洗牌...",
    tapToFlip: "点击卡片翻转！",
    revealed: (flipped: number, total: number) => `已翻开 ${flipped} / ${total}`,
    revealAll: "全部翻开",
    tapToReveal: "点击翻开",
    drawComplete: "抽签完成！",
    drawSummary: (total: number, win: number) => `共${total}个，中签${win}人`,
    winners: (n: number) => `中签（${n}人）`,
    losers: (n: number) => `未中（${n}人）`,
    copyResult: "复制结果",
    copied: "已复制！",
    redraw: "重新抽签",
    reset: "重新开始",
    faqTitle: "常见问题",
    faq: [
      {
        q: "如何使用抽签功能？",
        a: "输入选项（姓名、队名等）或选择预设，然后设定中签人数。点击开始抽签，牌会被洗混，点击每张牌来揭晓结果。",
      },
      {
        q: "抽签结果真的公平吗？",
        a: "是的！我们使用Fisher-Yates洗牌算法，每种结果的概率完全相等，结果不可预测也无法操控。",
      },
      {
        q: "适合哪些场合使用？",
        a: "适合决定获奖者、惩罚游戏、顺序决定、抽奖、派对游戏等各种场合。",
      },
    ],
    presets: [
      { label: "中签/未中", items: ["中签", "未中"] },
      { label: "一二三等/未中", items: ["一等奖", "二等奖", "三等奖", "未中"] },
      { label: "惩罚/免罚", items: ["惩罚", "免罚", "免罚", "免罚"] },
    ],
    copyLines: {
      header: "[抽签结果]",
      winners: (n: number, names: string) => `中签（${n}人）: ${names}`,
      losers: (n: number, names: string) => `未中（${n}人）: ${names}`,
      footer: "由PickPlay生成",
    },
  },
  es: {
    title: "Sorteo",
    subtitle: "Sorteo online justo y emocionante",
    quickStartPresets: "Presets rápidos",
    itemsLabel: "Agregar elementos",
    itemsMax: "(máx. 20)",
    itemPlaceholder: "Ingresa nombres (separados por coma)",
    addBtn: "Agregar",
    itemCount: (n: number) => `${n} elemento${n !== 1 ? "s" : ""}`,
    removeItem: (name: string) => `Quitar ${name}`,
    winnersLabel: "Número de ganadores",
    people: "",
    winnerRatio: (total: number, win: number, lose: number) =>
      `${win} ganador${win !== 1 ? "es" : ""} / ${lose} perdedor${lose !== 1 ? "es" : ""} de ${total}`,
    tooManyWinners: "Los ganadores deben ser menos que el total de elementos",
    startBtnNeedMore: "Agrega al menos 2 elementos",
    startBtnTooMany: "Reduce el número de ganadores",
    startBtn: "🎴 ¡Iniciar sorteo!",
    shuffling: "🔀 Mezclando cartas...",
    tapToFlip: "¡Toca una carta para voltearla!",
    revealed: (flipped: number, total: number) => `${flipped} / ${total} reveladas`,
    revealAll: "Revelar todo",
    tapToReveal: "Toca para revelar",
    drawComplete: "¡Sorteo completo!",
    drawSummary: (total: number, win: number) => `${win} ganador${win !== 1 ? "es" : ""} de ${total}`,
    winners: (n: number) => `Ganador${n !== 1 ? "es" : ""} (${n})`,
    losers: (n: number) => `Perdedor${n !== 1 ? "es" : ""} (${n})`,
    copyResult: "Copiar resultado",
    copied: "¡Copiado!",
    redraw: "Repetir sorteo",
    reset: "Empezar de nuevo",
    faqTitle: "Preguntas frecuentes",
    faq: [
      {
        q: "¿Cómo se usa el sorteo?",
        a: "Ingresa los elementos (nombres, equipos, etc.) o elige un preset, luego establece el número de ganadores. Pulsa Iniciar sorteo, las cartas se mezclarán y podrás tocarlas para revelar el resultado.",
      },
      {
        q: "¿El sorteo es realmente justo?",
        a: "¡Sí! Usamos el algoritmo de barajado Fisher-Yates, por lo que todos los resultados son igualmente probables. No hay resultados predeterminados.",
      },
      {
        q: "¿Para qué situaciones sirve?",
        a: "Selección de ganadores, penalizaciones, orden de turnos, rifas, juegos de fiesta y más. Usa los presets para sorteos de ganador/perdedor o 1°/2°/3° lugar.",
      },
    ],
    presets: [
      { label: "Gana / Pierde", items: ["Gana", "Pierde"] },
      { label: "1° / 2° / 3° / Pierde", items: ["1°", "2°", "3°", "Pierde"] },
      { label: "Penalti / Libre", items: ["Penalti", "Libre", "Libre", "Libre"] },
    ],
    copyLines: {
      header: "[Resultado del sorteo]",
      winners: (n: number, names: string) => `Ganador${n !== 1 ? "es" : ""} (${n}): ${names}`,
      losers: (n: number, names: string) => `Perdedor${n !== 1 ? "es" : ""} (${n}): ${names}`,
      footer: "Generado por PickPlay",
    },
  },
};

// ── Types ──────────────────────────────────────────────────────────────────

type Phase = "setup" | "draw" | "result";

interface DrawCard {
  id: number;
  label: string;
  isWinner: boolean;
  flipped: boolean;
}

// ── Constants ──────────────────────────────────────────────────────────────

const CHIP_COLORS = [
  "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
  "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300",
  "bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300",
  "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300",
  "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
  "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300",
  "bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300",
  "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300",
];

// ── Utilities ──────────────────────────────────────────────────────────────

function fisherYatesShuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function buildCards(items: string[], winnerCount: number): DrawCard[] {
  const results: boolean[] = [
    ...Array(winnerCount).fill(true),
    ...Array(items.length - winnerCount).fill(false),
  ];
  const shuffledResults = fisherYatesShuffle(results);
  return items.map((label, i) => ({
    id: i,
    label,
    isWinner: shuffledResults[i],
    flipped: false,
  }));
}

// ── Confetti ───────────────────────────────────────────────────────────────

const CONFETTI_COLORS = [
  "#FF6B6B", "#4ECDC4", "#FFE66D", "#A8E6CF", "#FF8B94",
  "#B5EAD7", "#FFDAC1", "#C7CEEA", "#F9C74F", "#90DBF4",
];

interface ConfettiPiece {
  id: number;
  x: number;
  color: string;
  size: number;
  delay: number;
  duration: number;
}

function Confetti({ active }: { active: boolean }) {
  const pieces = useMemo(() => Array.from({ length: 30 }, (_, i) => ({
    id: i,
    x: Math.random() * 100,
    color: CONFETTI_COLORS[i % CONFETTI_COLORS.length],
    size: 6 + Math.random() * 8,
    delay: Math.random() * 0.5,
    duration: 1.2 + Math.random() * 0.8,
    rotateDelta: Math.random() > 0.5 ? 360 : -360,
    borderRadius: Math.random() > 0.5 ? "50%" : "2px",
  })), []);

  if (!active) return null;

  return (
    <div className="pointer-events-none fixed inset-0 overflow-hidden z-50">
      {pieces.map((p) => (
        <motion.div
          key={p.id}
          initial={{ y: "-5vh", x: `${p.x}vw`, opacity: 1, rotate: 0, scale: 1 }}
          animate={{
            y: "110vh",
            opacity: [1, 1, 0],
            rotate: p.rotateDelta,
            scale: [1, 1.2, 0.8],
          }}
          transition={{ duration: p.duration, delay: p.delay, ease: "easeIn" }}
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: p.size,
            height: p.size,
            borderRadius: p.borderRadius,
            backgroundColor: p.color,
          }}
        />
      ))}
    </div>
  );
}

// ── Flip Card Component ────────────────────────────────────────────────────

interface FlipCardProps {
  card: DrawCard;
  index: number;
  onFlip: (id: number) => void;
  isShuffling: boolean;
  shuffleDelay: number;
  tapLabel: string;
}

function FlipCard({ card, index, onFlip, isShuffling, shuffleDelay, tapLabel }: FlipCardProps) {
  const handleClick = () => {
    if (!isShuffling && !card.flipped) onFlip(card.id);
  };

  return (
    <motion.div
      className="cursor-pointer"
      style={{ perspective: "1000px" }}
      initial={{ opacity: 0, y: 30, scale: 0.85 }}
      animate={
        isShuffling
          ? {
              opacity: 1,
              y: [0, -12, 8, -6, 0],
              x: [0, 10, -8, 5, 0],
              rotate: [0, 4, -3, 2, 0],
              scale: [1, 1.04, 0.97, 1.02, 1],
            }
          : { opacity: 1, y: 0, scale: 1 }
      }
      transition={
        isShuffling
          ? {
              duration: 0.6,
              delay: shuffleDelay,
              repeat: 3,
              repeatType: "mirror",
              ease: "easeInOut",
            }
          : { duration: 0.4, delay: index * 0.06, type: "spring", stiffness: 200, damping: 20 }
      }
      onClick={handleClick}
      whileHover={!card.flipped && !isShuffling ? { scale: 1.06, y: -4 } : {}}
      whileTap={!card.flipped && !isShuffling ? { scale: 0.96 } : {}}
    >
      <motion.div
        style={{ transformStyle: "preserve-3d", position: "relative", height: "120px" }}
        animate={{ rotateY: card.flipped ? 180 : 0 }}
        transition={{ duration: 0.55, ease: [0.23, 1, 0.32, 1] }}
      >
        {/* Front face */}
        <div
          style={{ backfaceVisibility: "hidden", WebkitBackfaceVisibility: "hidden" }}
          className="absolute inset-0 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex flex-col items-center justify-center shadow-md border-2 border-amber-300/50"
        >
          <span className="text-3xl select-none">🎴</span>
          <span className="text-white/80 text-xs font-semibold mt-1 select-none">{tapLabel}</span>
        </div>

        {/* Back face */}
        <div
          style={{
            backfaceVisibility: "hidden",
            WebkitBackfaceVisibility: "hidden",
            transform: "rotateY(180deg)",
          }}
          className={`absolute inset-0 rounded-2xl flex flex-col items-center justify-center shadow-md border-2 ${
            card.isWinner
              ? "bg-gradient-to-br from-amber-400 to-yellow-300 border-amber-300/70"
              : "bg-gradient-to-br from-slate-500 to-slate-600 border-slate-400/30"
          }`}
        >
          <span className="text-3xl select-none">{card.isWinner ? "🎉" : "😢"}</span>
          <span
            className={`text-sm font-bold mt-1 select-none ${
              card.isWinner ? "text-amber-900" : "text-slate-200"
            }`}
          >
            {card.label}
          </span>
        </div>
      </motion.div>
    </motion.div>
  );
}

// ── Main Page ──────────────────────────────────────────────────────────────

export default function DrawPage() {
  const locale = useLocale();
  const t = translations[locale];

  const [items, setItems] = useState<string[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [winnerCount, setWinnerCount] = useState(1);
  const [phase, setPhase] = useState<Phase>("setup");
  const [cards, setCards] = useState<DrawCard[]>([]);
  const [isShuffling, setIsShuffling] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // ── Setup helpers ──

  const addItems = useCallback(() => {
    const raw = inputValue.trim();
    if (!raw) return;
    const parsed = raw
      .split(/[,，、\n]/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && !items.includes(s));
    if (parsed.length > 0) setItems((prev) => [...prev, ...parsed].slice(0, 20));
    setInputValue("");
    inputRef.current?.focus();
  }, [inputValue, items]);

  const removeItem = useCallback((idx: number) => {
    setItems((prev) => {
      const next = prev.filter((_, i) => i !== idx);
      setWinnerCount((w) => Math.min(w, Math.max(1, next.length - 1)));
      return next;
    });
  }, []);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") { e.preventDefault(); addItems(); }
  };

  const applyPreset = (preset: { label: string; items: string[] }) => {
    setItems(preset.items);
    setWinnerCount(1);
  };

  // ── Draw flow ──

  const startDraw = useCallback(() => {
    if (items.length < 2) return;
    const built = buildCards(items, winnerCount);
    setCards(built);
    setPhase("draw");
    setIsShuffling(true);
    setTimeout(() => setIsShuffling(false), 3000);
  }, [items, winnerCount]);

  const flipCard = useCallback((id: number) => {
    setCards((prev) => prev.map((c) => c.id === id ? { ...c, flipped: true } : c));
  }, []);

  const flipAll = useCallback(() => {
    setCards((prev) => prev.map((c) => ({ ...c, flipped: true })));
  }, []);

  const allFlipped = cards.length > 0 && cards.every((c) => c.flipped);
  const hasWinnerFlipped = cards.some((c) => c.flipped && c.isWinner);

  const confettiTriggeredRef = useRef(false);
  useEffect(() => {
    if (hasWinnerFlipped && !confettiTriggeredRef.current) {
      confettiTriggeredRef.current = true;
      const t1 = setTimeout(() => setShowConfetti(true), 0);
      const t2 = setTimeout(() => setShowConfetti(false), 2500);
      return () => {
        clearTimeout(t1);
        clearTimeout(t2);
      };
    }
  }, [hasWinnerFlipped]);

  const resultTriggeredRef = useRef(false);
  useEffect(() => {
    if (allFlipped && phase === "draw" && !resultTriggeredRef.current) {
      resultTriggeredRef.current = true;
      const timer = setTimeout(() => setPhase("result"), 800);
      return () => clearTimeout(timer);
    }
  }, [allFlipped, phase]);

  const resetAll = () => {
    setItems([]);
    setInputValue("");
    setWinnerCount(1);
    setPhase("setup");
    setCards([]);
    setIsShuffling(false);
    setShowConfetti(false);
    setCopySuccess(false);
    confettiTriggeredRef.current = false;
    resultTriggeredRef.current = false;
  };

  const redraw = () => {
    confettiTriggeredRef.current = false;
    resultTriggeredRef.current = false;
    setShowConfetti(false);
    setCopySuccess(false);
    startDraw();
  };

  const copyResult = useCallback(async () => {
    const winners = cards.filter((c) => c.isWinner).map((c) => c.label);
    const losers = cards.filter((c) => !c.isWinner).map((c) => c.label);
    const lines = [
      t.copyLines.header,
      "",
      t.copyLines.winners(winners.length, winners.join(", ")),
      t.copyLines.losers(losers.length, losers.join(", ")),
      "",
      t.copyLines.footer,
    ];
    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch {
      // clipboard not available
    }
  }, [cards, t]);

  const canStart = items.length >= 2 && winnerCount >= 1 && winnerCount < items.length;
  const winners = cards.filter((c) => c.isWinner);
  const losers = cards.filter((c) => !c.isWinner);

  return (
    <PageTransition>
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-amber-50/30 to-orange-50/20 dark:from-slate-950 dark:via-amber-950/20 dark:to-orange-950/10">
        <Confetti active={showConfetti} />

        <div className="max-w-lg mx-auto px-4 py-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-8"
          >
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 shadow-lg mb-4">
              <span className="text-3xl">🎴</span>
            </div>
            <h1 className="text-3xl font-extrabold bg-gradient-to-r from-amber-500 to-orange-500 bg-clip-text text-transparent mb-2">
              {t.title}
            </h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm">
              {t.subtitle}
            </p>
          </motion.div>

          <AnimatePresence mode="wait">

            {/* ── SETUP PHASE ── */}
            {phase === "setup" && (
              <motion.div
                key="setup"
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -24 }}
                transition={{ duration: 0.3 }}
                className="space-y-4"
              >
                {/* Presets */}
                <div className="bg-white dark:bg-slate-800 rounded-2xl p-5 shadow-sm border border-slate-200 dark:border-slate-700">
                  <h2 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">
                    {t.quickStartPresets}
                  </h2>
                  <div className="flex flex-wrap gap-2">
                    {t.presets.map((preset) => (
                      <button
                        key={preset.label}
                        onClick={() => applyPreset(preset)}
                        className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                          JSON.stringify(items) === JSON.stringify(preset.items)
                            ? "bg-gradient-to-r from-amber-500 to-orange-500 text-white shadow-md scale-105"
                            : "bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 hover:bg-amber-50 dark:hover:bg-amber-900/30"
                        }`}
                      >
                        {preset.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Item input */}
                <div className="bg-white dark:bg-slate-800 rounded-2xl p-5 shadow-sm border border-slate-200 dark:border-slate-700">
                  <h2 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">
                    {t.itemsLabel} <span className="text-xs normal-case font-normal">{t.itemsMax}</span>
                  </h2>
                  <div className="flex gap-2">
                    <input
                      ref={inputRef}
                      type="text"
                      value={inputValue}
                      onChange={(e) => setInputValue(e.target.value)}
                      onKeyDown={handleKeyDown}
                      placeholder={t.itemPlaceholder}
                      className="flex-1 min-h-[48px] px-4 rounded-xl border border-slate-200 dark:border-slate-600 bg-slate-50 dark:bg-slate-700 text-slate-800 dark:text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-amber-400 text-sm"
                    />
                    <button
                      onClick={addItems}
                      className="min-h-[48px] px-5 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 text-white font-semibold text-sm hover:from-amber-600 hover:to-orange-600 transition-all active:scale-95 shadow-sm"
                    >
                      {t.addBtn}
                    </button>
                  </div>

                  {/* Item chips */}
                  <AnimatePresence>
                    {items.length > 0 && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        className="mt-4 flex flex-wrap gap-2"
                      >
                        {items.map((item, idx) => (
                          <motion.span
                            key={`${item}-${idx}`}
                            initial={{ opacity: 0, scale: 0.7 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 0.7 }}
                            transition={{ type: "spring", stiffness: 400, damping: 20 }}
                            className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-sm font-medium ${CHIP_COLORS[idx % CHIP_COLORS.length]}`}
                          >
                            {item}
                            <button
                              onClick={() => removeItem(idx)}
                              className="ml-0.5 w-4 h-4 rounded-full flex items-center justify-center opacity-60 hover:opacity-100 transition-opacity"
                              aria-label={t.removeItem(item)}
                            >
                              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
                              </svg>
                            </button>
                          </motion.span>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {items.length > 0 && (
                    <p className="mt-3 text-xs text-slate-400">{t.itemCount(items.length)}</p>
                  )}
                </div>

                {/* Winner count */}
                <div className="bg-white dark:bg-slate-800 rounded-2xl p-5 shadow-sm border border-slate-200 dark:border-slate-700">
                  <h2 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">
                    {t.winnersLabel}
                  </h2>
                  <div className="flex items-center justify-center gap-6">
                    <button
                      onClick={() => setWinnerCount((n) => Math.max(1, n - 1))}
                      disabled={winnerCount <= 1}
                      className="w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-700 hover:bg-amber-100 dark:hover:bg-amber-900/40 text-slate-700 dark:text-slate-200 text-2xl font-bold disabled:opacity-30 transition-colors flex items-center justify-center"
                    >
                      −
                    </button>
                    <div className="text-center">
                      <span className="text-5xl font-extrabold bg-gradient-to-r from-amber-500 to-orange-500 bg-clip-text text-transparent">
                        {winnerCount}
                      </span>
                      {t.people && (
                        <span className="text-slate-500 dark:text-slate-400 ml-1 text-lg">{t.people}</span>
                      )}
                    </div>
                    <button
                      onClick={() => setWinnerCount((n) => Math.min(Math.max(1, items.length - 1), n + 1))}
                      disabled={winnerCount >= items.length - 1 || items.length < 2}
                      className="w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-700 hover:bg-amber-100 dark:hover:bg-amber-900/40 text-slate-700 dark:text-slate-200 text-2xl font-bold disabled:opacity-30 transition-colors flex items-center justify-center"
                    >
                      +
                    </button>
                  </div>
                  {items.length >= 2 && (
                    <p className="text-center text-xs text-slate-400 mt-3">
                      {t.winnerRatio(items.length, winnerCount, items.length - winnerCount)}
                    </p>
                  )}
                  {winnerCount >= items.length && items.length > 0 && (
                    <p className="text-center text-xs text-rose-500 mt-1">
                      {t.tooManyWinners}
                    </p>
                  )}
                </div>

                {/* Ad: setup bottom */}
                <AdBanner format="horizontal" className="rounded-2xl bg-white/50 dark:bg-slate-800/50 p-2" />

                {/* Start button */}
                <motion.button
                  onClick={startDraw}
                  disabled={!canStart}
                  whileHover={canStart ? { scale: 1.02 } : {}}
                  whileTap={canStart ? { scale: 0.97 } : {}}
                  className="w-full min-h-[56px] rounded-2xl bg-gradient-to-r from-amber-500 to-orange-500 text-white font-bold text-lg shadow-lg hover:from-amber-600 hover:to-orange-600 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  {items.length < 2
                    ? t.startBtnNeedMore
                    : winnerCount >= items.length
                    ? t.startBtnTooMany
                    : t.startBtn}
                </motion.button>
              </motion.div>
            )}

            {/* ── DRAW PHASE ── */}
            {phase === "draw" && (
              <motion.div
                key="draw"
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -24 }}
                transition={{ duration: 0.3 }}
                className="space-y-4"
              >
                <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-sm border border-slate-200 dark:border-slate-700">
                  {/* Status bar */}
                  <div className="text-center mb-6">
                    {isShuffling ? (
                      <motion.p
                        animate={{ opacity: [1, 0.5, 1] }}
                        transition={{ duration: 0.7, repeat: Infinity }}
                        className="text-lg font-bold text-amber-500"
                      >
                        {t.shuffling}
                      </motion.p>
                    ) : (
                      <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ type: "spring", stiffness: 200 }}
                      >
                        <p className="text-lg font-bold text-slate-700 dark:text-slate-200">
                          {t.tapToFlip}
                        </p>
                        <p className="text-sm text-slate-400 mt-1">
                          {t.revealed(cards.filter((c) => c.flipped).length, cards.length)}
                        </p>
                      </motion.div>
                    )}
                  </div>

                  {/* Card grid */}
                  <div className={`grid gap-3 ${cards.length <= 4 ? "grid-cols-2" : cards.length <= 6 ? "grid-cols-3" : "grid-cols-4"}`}>
                    {cards.map((card, idx) => (
                      <FlipCard
                        key={card.id}
                        card={card}
                        index={idx}
                        onFlip={flipCard}
                        isShuffling={isShuffling}
                        shuffleDelay={idx * 0.04}
                        tapLabel={t.tapToReveal}
                      />
                    ))}
                  </div>

                  {/* Flip all button */}
                  {!isShuffling && !allFlipped && (
                    <motion.button
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.4 }}
                      onClick={flipAll}
                      className="w-full mt-6 min-h-[48px] rounded-xl bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 font-semibold text-sm hover:bg-slate-200 dark:hover:bg-slate-600 transition-all active:scale-95"
                    >
                      {t.revealAll}
                    </motion.button>
                  )}
                </div>
              </motion.div>
            )}

            {/* ── RESULT PHASE ── */}
            {phase === "result" && (
              <motion.div
                key="result"
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -24 }}
                transition={{ duration: 0.4 }}
                className="space-y-4"
              >
                {/* Result header */}
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.1, type: "spring", stiffness: 200 }}
                  className="text-center py-2"
                >
                  <motion.div
                    animate={{ rotate: [0, -10, 10, -5, 5, 0] }}
                    transition={{ duration: 0.7, delay: 0.2 }}
                    className="text-5xl mb-3"
                  >
                    🎊
                  </motion.div>
                  <h2 className="text-2xl font-extrabold text-slate-800 dark:text-white">
                    {t.drawComplete}
                  </h2>
                  <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">
                    {t.drawSummary(cards.length, winners.length)}
                  </p>
                </motion.div>

                {/* Winners */}
                <motion.div
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 }}
                  className="bg-gradient-to-br from-amber-50 to-orange-50 dark:from-amber-950/40 dark:to-orange-950/40 rounded-2xl p-5 border border-amber-200/60 dark:border-amber-700/40"
                >
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xl">🎉</span>
                    <h3 className="text-base font-bold text-amber-700 dark:text-amber-300">
                      {t.winners(winners.length)}
                    </h3>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {winners.map((c, i) => (
                      <motion.span
                        key={c.id}
                        initial={{ opacity: 0, scale: 0.7 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.3 + i * 0.08, type: "spring", stiffness: 300 }}
                        className="px-4 py-2 rounded-full bg-gradient-to-r from-amber-400 to-orange-400 text-white font-bold text-sm shadow-sm"
                      >
                        {c.label}
                      </motion.span>
                    ))}
                  </div>
                </motion.div>

                {/* Losers */}
                {losers.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, y: 16 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.35 }}
                    className="bg-white dark:bg-slate-800 rounded-2xl p-5 shadow-sm border border-slate-200 dark:border-slate-700"
                  >
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-xl">😢</span>
                      <h3 className="text-base font-bold text-slate-600 dark:text-slate-300">
                        {t.losers(losers.length)}
                      </h3>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {losers.map((c, i) => (
                        <motion.span
                          key={c.id}
                          initial={{ opacity: 0, scale: 0.7 }}
                          animate={{ opacity: 1, scale: 1 }}
                          transition={{ delay: 0.45 + i * 0.06, type: "spring", stiffness: 300 }}
                          className="px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 font-medium text-sm"
                        >
                          {c.label}
                        </motion.span>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Ad: after results */}
                <AdBanner format="rectangle" className="mt-6 rounded-2xl bg-white/50 dark:bg-slate-800/50 p-2" />

                {/* Action buttons */}
                <motion.div
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.5 }}
                  className="grid grid-cols-3 gap-3"
                >
                  <button
                    onClick={copyResult}
                    className={`min-h-[48px] rounded-xl font-semibold text-sm transition-all active:scale-95 border ${
                      copySuccess
                        ? "bg-emerald-500 text-white border-emerald-500"
                        : "bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 border-slate-200 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-700"
                    }`}
                  >
                    {copySuccess ? t.copied : t.copyResult}
                  </button>
                  <button
                    onClick={redraw}
                    className="min-h-[48px] rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 text-white font-semibold text-sm hover:from-amber-600 hover:to-orange-600 transition-all active:scale-95 shadow-sm"
                  >
                    {t.redraw}
                  </button>
                  <button
                    onClick={resetAll}
                    className="min-h-[48px] rounded-xl bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 font-semibold text-sm hover:bg-slate-200 dark:hover:bg-slate-600 transition-all active:scale-95"
                  >
                    {t.reset}
                  </button>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Ad: page bottom */}
          <AdBanner format="in-article" className="mt-4 rounded-2xl bg-white/50 dark:bg-slate-800/50 p-2" />

          {/* FAQ Section */}
          <section className="mt-16 mb-8">
            <h2 className="text-2xl font-bold mb-6 text-center text-slate-800 dark:text-slate-100">
              {t.faqTitle}
            </h2>
            <div className="space-y-4">
              {t.faq.map((item, i) => (
                <details
                  key={i}
                  className="group bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden"
                >
                  <summary className="flex items-center justify-between p-5 cursor-pointer font-semibold text-slate-700 dark:text-slate-200 hover:text-amber-500 transition-colors">
                    {item.q}
                    <svg className="w-5 h-5 shrink-0 transition-transform group-open:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </summary>
                  <div className="px-5 pb-5 text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
                    {item.a}
                  </div>
                </details>
              ))}
            </div>
          </section>
        </div>
      </div>
    </PageTransition>
  );
}
